### ISSUE TITLE
Could not locate that visualization

### ISSUE THREAD

**Issue by bwa** [WASdev/sample.logstash.collector#1]
The Kibana dashboard seems to reference unknown visualization. getting a lot of empty boxes with messages like : Could not locate that visualization (id: serversTable)

![kibana](https://cloud.githubusercontent.com/assets/170977/22414173/c1cda5de-e6bd-11e6-93f6-424875659fd4.jpg)

**Comment by brennanNichyporuk** [comment]
If you go to Settings > Objects > Visualizations, do you see the missing visualizations? Either way, you might want to try deleting all of the dashboards/searches/visualizations and importing the liberty-kibana4.json (from the version-1.0 folder for production, from the version-1.1 folder for beta) again. All of the necessary objects (including the visualizations) are included in that json.

**Comment by umairsuri** [comment]
I  have the same issue i cannot import the visualization after i had to remove all the indices and indexes  to get the geo ip location field updated and take effect . I did not export it before deleting it and now when i'm trying to import the dashboard it gives warning "  
Saved Objects: Could not locate that index-pattern-field (id: DST )"  which usually imports visualization and when clicking ok and refreshing page its showing the dashboards however now its giving me error "Could not locate that visualization (id: ASA-Timeline-slash-Action-lines)" . Please help and advise

**Comment by fmhwong** [comment]
@umairsuri Are you having issue with importing the dashboards for IBM WebSphere Liberty provided in this repository?

**Comment by fmhwong** [comment]
Close due to inactivity

**Comment by umairsuri** [comment]
My Apologies for the delay i missed the email some how.
No but I got similar errors as shown in the screenshot above. I have deleted the indexes and index template to update the Logstash template to have Geoip location field type from string. I did not imported my index patterns and searches and dashboards.
Please advise & let me know if you need me to open a separate thread. 
Thank you 
Umair

**Comment by fmhwong** [comment]
@umairsuri If you are having trouble with the sample dashboards provided by this repository, please open a new issue.

**Comment by umairsuri** [comment]
@fmhwong  What do you mean by "Sample dashboard" and repository?  Also my question is about custom dashboard and visualizations I'm trying to import but failing with an error "Could not locate visualization id " "" as shown in the attached pic in this thread,

**Comment by fmhwong** [comment]
@umairsuri The sample files we provided in this github repository are meant for the Liberty logstashCollector-1.0/1.1 feature sending log records to Logstash.  If you have trouble with using logstashCollector feature with the files provided in this repository, please open a new issue with detailed step by step instructions on how to reproduce the problem.  Screen shots are helpful too.

**Comment by umairsuri** [comment]
here is the link to the new issue opened for the very same
Kibana Dashboard "Could not locate that visualization (id: "  #18879
