### ISSUE TITLE
Kibana 7 dashboard not working

### ISSUE THREAD

**Issue by mbuccarello** [WASdev/sample.logstash.collector#18]
Hi,

I did a fresh installation of ELK stack and I configured liberty with logstashcollector-1.0

Kibana received correctly all information but dashboard are not working and during the import the field datetime isn't recognized.

**Comment by donbourne** [comment]
Two things to check...
1) ensure that you have started Liberty with the logstashCollector-1.0 feature before trying to import your dashboard into Kibana
2) refresh the index in Kibana to make sure Kibana is aware of all fields before trying to import your dashboard.

You should be able to see the fields you are looking for in the Discover tab in Kibana before you do your import.  If you hit the button to refresh the fields in your index you should also see that those fields are listed in your index before you do the import.

Does that help?

**Comment by mbuccarello** [comment]
Hello, I did kibana refresh and my listed object are 160, I manually changed  2 dashboard and now accesslog and problems dashboard seems working.

For more detail about the issues here some screenshoot

https://community.ibm.com/community/user/imwuc/communities/community-home/digestviewer/viewthread?MessageKey=61e02bcb-916c-49fd-a4d6-0454bd1eb0e5&CommunityKey=5c4ba155-561a-4794-9883-bb0c6164e14e&tab


If you want I can share my updated dashboard.

Thanks

**Comment by donbourne** [comment]
Apologies, I think I see a mistake in our logstash template file.  For some reason the template is using ibm_* field names (which would be correct for logstashCollector-1.1 but not for logstashCollector-1.0).  

Will get that fixed and new files posted using this issue.

**Comment by mbuccarello** [comment]
Thank you for your quick answer, here I uploaded my patched version.

https://community.ibm.com/community/user/imwuc/communities/community-home/digestviewer/viewthread?GroupId=19&MessageKey=6b3fbc8f-79ca-40b5-9bb8-7e0bf891b935&CommunityKey=5c4ba155-561a-4794-9883-bb0c6164e14e&tab=digestviewer&ReturnUrl=%2fcommunity%2fuser%2fimwuc%2fcommunities%2fcommunity-home%2fdigestviewer%3fcommunitykey%3d5c4ba155-561a-4794-9883-bb0c6164e14e%26tab%3ddigestviewer

Is in my last post so you can submit eventually a pull request if required.

**Comment by donbourne** [comment]
@mbuccarello thanks for your patience on this one.  We just merged a PR to resolve this.  Please re-open (or open a new issue) if you see anything wrong now.
