### ISSUE TITLE
Dashboard says loading - but nothing loads

### ISSUE THREAD

**Issue by ashah007** [WASdev/sample.logstash.collector#9]
I am on WAS Liberty 8.5.5.9. I have loaded logStash Collector 1.0. I am working with ELS Stack of 5.3.3. I have configured all as per this instructions:
https://www.ibm.com/support/knowledgecenter/en/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_analytics_logstash.html

I can also data coming from WAS into Logstash and then getting into ES. I can also see data in kibana dashboard. I then loaded Dashboard from sample.logstash.collector/version-1.0/Kibana5/Beta/20170516/liberty-kibana5.json

But now when i try to load dashboard, it says loading nothing happens. When i click on some visualiazation such as "access log count", it works, but doesnt load some others.

I also see errors such as "visualize field is a required parameter". Any thoughts would be appreciated

**Comment by fmhwong** [comment]
@ashah007 Sorry for the late reply.  Are you still having issue with the dashboards?

**Comment by ashah007** [comment]
Project is over. Thanks for your response

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
